//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryEntity
    {
        public CategoryEntity()
        {
            this.ToDoItems = new HashSet<ToDoItemEntity>();
        }
    
        public string category { get; set; }
        public System.DateTime created_on { get; set; }
    
        public virtual ICollection<ToDoItemEntity> ToDoItems { get; set; }
    }
}
