//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoItemEntity
    {
        public System.Guid id { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public byte IsComplete { get; set; }
        public System.DateTime created_on { get; set; }
        public int recurrence { get; set; }
        public string description { get; set; }
    
        public virtual CategoryEntity CategoryEntity { get; set; }
    }
}
